class OHRM_TEST_Data():
    url = 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login'
    username = 'Admin'
    password = 'admin123'
    invpassword = 'Invalid Password'
    FirstName = 'All'
    MiddleName = 'Is'
    LastName = 'Well'
    Emp_ID = '99887'
    Login_ID = 'AllIsWell'
    Login_password = 'Test123123!'
    Search_Name = 'All Is Well'
    New_LastName = 'Good'
    Delete_Search_Name = 'All Is Good'
